# Generated by Django 2.2.6 on 2020-05-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_set_question',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question_set_question',
            old_name='question_set_id',
            new_name='question_set',
        ),
    ]
