# Generated by Django 2.2.6 on 2020-05-17 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20200510_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_set_question',
            options={'verbose_name': 'Question & Question Set Manage', 'verbose_name_plural': 'Question & Question Set Manage'},
        ),
        migrations.AddField(
            model_name='question_set_question',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question_set',
            name='name',
            field=models.CharField(help_text='Enter meaningfull Question-Set Name like "2020-Bengali-Set-I"', max_length=150),
        ),
    ]
